name: reco-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.12
  - pip
  - pip:
      - dnspython==2.1.0
      - fastapi==0.68.1
      - motor==2.3.0
      - numpy==1.22.2
      - pandas==1.4.1
      - pydantic==1.8.2
      - python-dotenv==0.19.0
      - pymongo==3.11.1
      - pytest==7.0.1
      - pytest-asyncio==0.18.1
      - pytest-env==0.6.2
      - requests==2.27.1
      - scipy==1.8.0
      - starlette==0.14.2
      - uvicorn==0.15.0
